[General]
Name = "Default"
Version = "0.9"
Creator = "Mr-Ojii"

[SongSelect]
BackBoxTextCorrectionY = 40
RotateChara = [ "≠", "【", "】", ":", "ー", "-", "~", "～", "<", ">", "(", ")", "[", "]", "「", "」", "（", "）", "＜", "＞", " ", "　", "『", "』" ]

[Game]
NotesAnime = true
StageText = "n曲目"
