[General]
Name = "Default"
Version = "0.9"
Creator = "Mr-Ojii"

[SongSelect]
BackBoxTextCorrectionY = 40
RotateChara = [ "≠", "【", "】", ":", "ー", "-", "~", "～", "<", ">", "(", ")", "[", "]", "「", "」", "（", "）", "＜", "＞", " ", "　", "『", "』" ]
CorrectionXChara = [ ".", "ッ", "ェ", "ョ", "ャ", "[", "]" ]
CorrectionXCharaValue = [ 10, 5, 7, 7, 7, -10, -10 ]

[Game]
NotesAnime = true
StageText = "n曲目"
