name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        config:
          - { platform: win-x86,     os-platform: win }
          - { platform: win-x64,     os-platform: win }
          - { platform: osx-x64,     os-platform: osx }
          - { platform: osx-arm64,   os-platform: osx }
          - { platform: linux-x64,   os-platform: linux }
          - { platform: linux-arm64, os-platform: linux }

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Build
      run: dotnet publish TJAPlayer3-f -o publish -r ${{ matrix.config.platform }} -p:PublishSingleFile=true --configuration Release --self-contained true
