name: build

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [win-x86, win-x64, linux-x64, osx-x64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
    - name: Build
      run: dotnet publish TJAPlayer3-f -o publish -r ${{ matrix.platform }} -p:PublishSingleFile=true --configuration Release --self-contained true
      
