name: build

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [win-x86, win-x64, linux-x64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set REV_LIST_COUNT
      id: rev
      run: |
        cd ${{ github.workspace }}
        REVCOUNT=`git rev-list --count HEAD`
        echo "::set-output name=REV_LIST_COUNT::${REVCOUNT}"
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet publish TJAPlayer3-f -o Test/net6.0 -r ${{ matrix.platform }} -p:PublishSingleFile=true --configuration Release --self-contained true
    - name: Remove Folder
      uses: JesseTG/rm@v1.0.0
      with:
        path: Test/net6.0/${{matrix.platform}}
    - name: Remove Folder
      run: |
        cd ${{ github.workspace }}/Test/net6.0/dll
        echo "#!"/bin/sh > del.sh
        echo "for filename in *" >> del.sh
        echo "do" >> del.sh
        echo "  ""if [ ""$""{filename}"" ""!""="" ""${{matrix.platform}}"" ] ; then" >> del.sh
        echo "    rm -rf ""$""{filename}" >> del.sh
        echo "    "echo" ""$""{filename}" >> del.sh
        echo "  fi" >> del.sh
        echo "done" >> del.sh
        sh del.sh
    - name: Remove Folder
      run: |
        cd ${{ github.workspace }}/Test/net6.0/ffmpeg
        echo "#!"/bin/sh > del.sh
        echo "for filename in *" >> del.sh
        echo "do" >> del.sh
        echo "  ""if [ ""$""{filename}"" ""!""="" ""${{matrix.platform}}"" ] ; then" >> del.sh
        echo "    rm -rf ""$""{filename}" >> del.sh
        echo "    "echo" ""$""{filename}" >> del.sh
        echo "  fi" >> del.sh
        echo "done" >> del.sh
        sh del.sh
    - name: Upload artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: TJAPlayer3-f-Release-${{ matrix.platform }}-${{ steps.rev.outputs.REV_LIST_COUNT }}
        path: Test
